spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa

    logging:
      level:
        org:
          hibernate:
            type:
              descriptor:
                sql: trace